export const PRACTICES = {
    "types": [
      { "name":"Direito Fiscal", "description": ["Sendo esta a área de especialização da equipa da CTM Advogados, permite-nos responder com eficácia à generalidade das necessidades dos Clientes de âmbito contencioso, nomeadamente através do patrocínio de procedimentos de reclamação, de processo de impugnação ou de oposição fiscais, bem como de consultoria tendente a uma maior eficiência fiscal."] },
      { "name":"Direito da Insolvência", "description":["Sabendo que, apesar de vivermos um período de ligeiro crescimento económico, e que os tempos mais duros da crise já passaram, também não podemos negar que a maior facilitação do acesso ao crédito por parte de bancos e instituições financeiras estão a “revitalizar” alguns erros do passado. Ora, com o crescente sobreendividamento de famílias e empresas, estas surgem, na maioria dos casos, como a parte mais fragilizada. Deste modo, a CTM Advogados irá pugnar sempre pela proteção do devedor insolvente, tendo em vista a satisfação das suas legítimas pretensões, nunca olvidando a finalidade deste Direito, que é a satisfação dos interesses dos credores."]  },
      { "name":"Recuperação de Créditos", "description":["O apoio jurídico na resolução destes problemas oferece, primeiramente, um serviço que vá ao encontro de uma solução pela via do acordo com os devedores. Frustrando-se um eventual acordo, a CTM Advogados estará sempre disponível em enveredar pela via judicial, intentando acções a fim de defender sempre o superior interesse do cliente a melhor alcançar a recuperação do seu crédito."]  }, 
      { "name":"Direito dos Seguros", "description":["A CTM Advogados presta aconselhamento jurídico nesta área, nomeadamente nos seguros do ramo “não vida”, com foco nos seguros de responsabilidade civil automóvel, procurando sempre a melhor solução possível que sirva as pretensões dos nossos clientes, de forma a obter uma justa reparação e determinação das indemnizações que lhes devem ser atribuídas, bem como seguros de acidentes de trabalho, pugnando por eventuais direitos que assistem ao trabalhador sinistrado e/ou sua família, designadamente assistência clínica, reparação, indemnização e reabilitação profissional."]  },
      { "name":"Direito da Família", "description":["Com rigor e ética na abordagem profissional em matérias de maior sensibilidade, a CTM Advogados estará atenta e completamente disponível a fim de responder as necessidades individuais do cliente em assuntos de natureza tão delicada. Divórcio (com e sem mútuo consentimento), Direitos dos menores (tutela, direitos de visita, regulação da responsabilidade parental), adopção e apoio jurídico em situações de união de facto."]  },
      { "name":"Direitos Reais e Imobiliário", "description":["Sendo o Direito de Propriedade reconhecido ao seu titular, tendo em conta o aproveitamento pleno da utilidade do bem, sempre dentro dos limites da lei, a CTM Advogados encontra-se disponível para dar apoio e aconselhamento na discussão, análise e elaboração desses contratos, bem como patrocinar acções destinadas a fazer valer não só o seu Direito de Propriedade, mas também o usufruto, uso e habitação servidões prediais, bem como qualquer tipo de litigio de vizinhança.", "No ambito do alojamento local, a CTM Advogados está a par da crescente importancia que este sector está cada vez mais a ter a economia nacional, de modo que toda a equipa está a par das recentes alterações legislativas acerca da exploração deste tipo de estabelecimentos, pelo que nos encontramos disponiveis para assessorar qualquer tipo de investimento."]  },
      { "name":"Direito Penal e Contraordenacional", "description":["A CTM Advogados está ao dispor e pronta para lidar com a responsabilidade criminal e contra-ordenacional de pessoas singulares, empresas e entidades colectivas, quer na defesa dos arguidos, quer no patrocínio dos denunciantes/demandantes. No domínio contra-ordenacional, a CTM Advogados possui experiência quer na fase administrativa, quer na fase judicial de impugnação das decisões proferidas pelas autoridades administrativas.", "Os advogados assumem uma defesa intransigente dos seus clientes, arguidos ou ofendidos, nas diferentes etapas processuais do processo criminal, designadamente elaboração de queixas-crimes, contestação, elaboração de contestação à acusação e ao pedido de indemnização cível."]  },
      { "name":"Direito Comercial e Societário", "description":["Prestamos acessoria jurídica no âmbito de constituição de sociedades, elaboração e alteração de contratos sociais, aumentos e reduções de capital, transformação, dissolução e liquidação das mesmas, bem como no âmbito da contratação relativa a estabelecimentos comerciais (trespasse, cessão de exploração)."]  },
      { "name":"Direito do Trabalho", "description":["Cientes de que todas as questões emergentes das relações laborais assumem vital importância, prestamos acessoria jurídica quer a particulares quer a empresas em diversas matérias relacionadas com vínculos contratuais, processos disciplinares, despedimentos, acidentes de trabalho, contencioso laboral e processo de contraordenação relacionados com matéria laboral."]  },
      { "name":"Direito do Administrativo", "description": ["Na área de Direito Administrativo, a CTM advogados presta serviço em todo o tipo de procedimento e processo administrativo tanto na vertente de reclamações administrativas como pela via contenciosa nos Tribunais Administrativos."] },
      { "name":"Direito dos Estrangeiros e Imigração", "description":["Portugal nunca esteve tanto na moda como agora. A excelente imagem que o país tem no exterior, pela sua beleza, o seu clima ameno, a segurança e até pela confiança que se nota na generalidade da população de que os tempos de crise “já passaram” e que retomamos um caminho de prosperidade económica, acabam por atrair vários estrangeiros para estudar, trabalhar ou gozar a sua reforma. Na CTM Advogados estamos atentos ao fenómeno da imigração, pelo que toda a equipa está preparada para prestar todo o apoio jurídico no que concerne à entrada e permanência, bem como à sua saída do território nacional, aquisição de nacionalidade e assistência no processo de obtenção de Autorização de Residência para actividade de investimento (\"Golden Visa\")."] },
      { "name":"Propriedade Intelectual e Industrial", "description":["A CTM Advogados encontra-se ao dispor em todos os assuntos de propriedade intelectual e industrial, designadamente, marcas, patentes, desenhos e modelos industriais, logotipos, firmas comerciais e denominações sociais, bem como na defesa do direito de propriedade da marca, patente, desenho ou modelo."]  },
      { "name":"Registos", "description":["Fruto do decreto-lei n.º 76-A/2006 de 29 de Março, o mesmo conferiu aos advogados a faculdade defazer reconhecimentos com menções especiais por semelhança e certificar ou fazer e certificar traduções de documentos.\n - Autenticação de documentos.\n - Certificação de documentos e de traduções.\n - Marcação, acompanhamento e minutas de escrituras.\n - Naturalizações e alterações de nome.\n - Divórcios e separações de pessoas e bens, por mútuo consentimento.","A equipa da CTM Advogados, utilizando todos os meios ao seu alcance e com celeridade, elaborará em seu nome os registos, informações e pedidos de registo que necessitar, nomeadamente:\n - Registo predial, automóvel e comercial.\n - Registo civil.\n - Habilitação de herdeiros no estrangeiro. Nem sempre é fácil aos portugueses que residem no estrangeiro e aos estrangeiros não residentes no país celebrar escrituras de habilitação de herdeiros nalguns consulados portugueses. Cuidaremos desses assuntos por si."] }
    ]
  };